baseURL = "https://vsaxena2711.github.io/"
languageCode = "en-us"
title = "AInfraMinds"
theme = "PaperMod"

[pagination]
  pagerSize = 5

[params]
  hideTitle = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "auto"
  env = "production"
  gtagID = "G-Q9KS4FM50S"
  customCSS = ["css/custom.css"]

mainSections = []

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
