baseURL = 'https://vsaxena2711.github.io/'
languageCode = 'en-us'
title = 'InfraMind'
theme = 'PaperMod'
pagerSize = 5

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "auto"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "iac"
    name = "IaC (Terraform)"
    url = "/iac/"
    weight = 2

  [[menu.main]]
    identifier = "ai"
    name = "Azure AI"
    url = "/ai/"
    weight = 3

[cascade]

  [[cascade.cascade]]
    _target = { path = "/iac/**" }
    showInHome = false

  [[cascade.cascade]]
    _target = { path = "/ai/**" }
    showInHome = false

  [[cascade.cascade]]
    _target = { path = "/about.md" }
    showInHome = false